### ISSUE TITLE
The % counter jumps back and forth (community spotted 87-89 back and forth)

### ISSUE THREAD

**Issue by Witos89** [radixdlt/mtps#53]
Will updated with images/videos if possible

**Comment by Witos89** [comment]
https://wetransfer.com/downloads/45019e135515b3418eda44346d92818d20190619163600/a90fb8?src=dnl on video

**Comment by laszlourszuly** [comment]
Thanks for submitting this issue @Witos89! This behaviour is due to node behaviour to the end of the test, when only the "heavy atoms" remain to validate. Those atoms involve a lot of nodes in the validation process. Nodes that no longer progress at the previously extrapolated speed, which manifests itself in the progress seemingly dropping.

We're looking into how to mitigate this behaviour. One approach to consider is to tweak the extrapolation algorithm to be a bit more restrictive in its prognosis.
